### ISSUE TITLE
在使用hooks的时候，为什么最好不要在useEffect里面发起异步请求，在useEffect里面发起异步请求有什么弊端吗，除了使用ReactQuery外，还能怎么发起请求比较好呢

### ISSUE THREAD

**Issue by YuuJinK** [shean012/blog#10]

**Comment by shean012** [comment]
这个是一个好问题，但回答这个问题的话，先说明一点，下面提及到的情况并不完全针对 函数式组件，类组件中其实同样存在相似的问题。
首先回答最简单的问题：
除了使用ReactQuery外，还能怎么发起请求比较好呢？（第三问）
答： [useSWR](https://swr.vercel.app/) 这个库同样可以达到类似的效果；
然后是第一和第二个问题：
其实第一问和第二问意思差不多，为了更好回答你的问题，我分个角度回答你的问题
1. 什么场景下在 `useEffect` 下发请求相对合理
2. 什么场景下在 `useEffect` 下发请求不太友好
3. 在useEffect中发起请求不好的友好的地方

答： 1. 如果页面只是进入的时候，需要请求一下服务端记录一下数据，埋点等情况，其实写在 useEffect 中，并没有什么问题的。完全可以这样做。
2.  但如果我们的异步请求是依赖某一个变量，进行变化的话。这样就不应该使用 `useEffect` 进行异步请求。因为这样会存在不稳定的情况。因为随着业务逻辑的发展，我们的判断逻辑，或者依赖项会越来越来多，这样会导致我们的函数难以维护，例如我们的 `useEffect` 依赖了 A , B , C , D 四个值，但如果A等于0时，C改变了。不会触发更新，这样的逻辑越来越多的情况下。函数就十分容易出错，所以这个时候，我们应当考虑，这个异步函数，是否属于 `Event handlers` 如果是，那就交由时间的回调函数信息异步操作，而不是使用 `useEffect`。
3. 除了 事件 应该交由回调函数发请求的场景外，`useEffect` 因为没有缓存的功能，当我切换了页卡或发生路由跳转，它都需要重现发起请求，这样明显是不够友好的。而且页面中的请求并不是全部都在父组件中发起的。这样会导致  `request waterfalls` 的问题，父组件 `mount` 后，执行 `useEffect`，请求数据。数据返回后重新渲染父组件，然后子组件`mount`，子组件的 `useEffect` 执行，请求数据。数据返回后重新渲染子组件。这样一层层的递进。导致整个页面的渲染是十分低效的。所以不推荐在 useEffect 中发起请求。因为 `useEffect` 的执行时机是在 页面 `render` 后执行的。如果在这里发起请求，就会有这样的问题。
当然你肯定觉得奇怪，如果不在这里发起请求，那该如何做，才能避免这种低效的请求方式？ssr 其实就是在根源上解决这个问题的。因为用户看到页面的时候，数据已经是返回了的。但是这个做法十分昂贵。但是如果我们在页面没被渲染的时候就获取到数据了，是不是解决了这个问题了呢？
